# Generated by Django 5.1.5 on 2025-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('servico', models.CharField(max_length=100)),
                ('data_marcada', models.DateField()),
                ('horario_marcado', models.TimeField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
