# Generated by Django 4.2.19 on 2025-02-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0002_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=50)),
                ('total_horas', models.TimeField()),
            ],
        ),
    ]
