# Generated by Django 4.2.19 on 2025-02-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0003_db_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_servico',
            name='total_horas',
            field=models.IntegerField(),
        ),
    ]
