# Generated by Django 4.2.19 on 2025-02-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0004_alter_db_servico_total_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='horas_ocupadas',
            field=models.IntegerField(default=1),
        ),
    ]
